### ISSUE TITLE
Build fail on macOS and win10

### ISSUE THREAD

**Issue by DooblyNoobly** [kristjank/ark-net#2]
When building from VS on both win10 and macOS platform I receive build error related to the main ark-net solution. Here is the console output:

```
Target PostBuildEvent:
    REM Create a NuGet package for this project and place the .nupkg file in the project's output directory.
    REM If you see this in Visual Studio's Error List window, check the Output window's Build tab for the actual error.
    ECHO Creating NuGet package in Post-Build event...
    PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/_CreateNewNuGetPackage/DoNotModify/CreateNuGetPackage.ps1' -ProjectFilePath '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/ark-net.csproj' -OutputDirectory '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/bin/Debug/' -BuildConfiguration 'Debug' -BuildPlatform 'AnyCPU'"
    /var/folders/6r/wkww53sj6gbf1cpmj2lq7ygr0000gn/T/tmp69086b90510749819e89e1ac125a4306.exec.cmd: line 5: unexpected EOF while looking for matching `''
    /var/folders/6r/wkww53sj6gbf1cpmj2lq7ygr0000gn/T/tmp69086b90510749819e89e1ac125a4306.exec.cmd: line 6: syntax error: unexpected end of file
    /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: The command "REM Create a NuGet package for this project and place the .nupkg file in the project's output directory.
    /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: REM If you see this in Visual Studio's Error List window, check the Output window's Build tab for the actual error.
    /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: ECHO Creating NuGet package in Post-Build event...
    /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/_CreateNewNuGetPackage/DoNotModify/CreateNuGetPackage.ps1' -ProjectFilePath '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/ark-net.csproj' -OutputDirectory '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/bin/Debug/' -BuildConfiguration 'Debug' -BuildPlatform 'AnyCPU'"" exited with code 1.
Done building target "PostBuildEvent" in project "ark-net.csproj" -- FAILED.

Done building project "ark-net.csproj" -- FAILED.

Build FAILED.

Core/PeerApi.cs(101,21,101,26): warning CS0162: Unreachable code detected
/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: The command "REM Create a NuGet package for this project and place the .nupkg file in the project's output directory.
/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: REM If you see this in Visual Studio's Error List window, check the Output window's Build tab for the actual error.
/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: ECHO Creating NuGet package in Post-Build event...
/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5036,5): error MSB3073: PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/_CreateNewNuGetPackage/DoNotModify/CreateNuGetPackage.ps1' -ProjectFilePath '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/ark-net.csproj' -OutputDirectory '/Users/doob/Desktop/UnityBlock/ark-net/ark-net/bin/Debug/' -BuildConfiguration 'Debug' -BuildPlatform 'AnyCPU'"" exited with code 1.
    1 Warning(s)
    1 Error(s)
```

**Comment by kristjank** [comment]
Thank you for this // will look into it.

Can you try to install the full .NET framework - at least on windows... from your logs I see that you have errors in MONO framework, maybe the case for error lies there.

In the meanwhile - may i suggest  that you:
1. checkout from source
2. install NBITCOIN nuget package
3. try to do a build...

NuGET is packaged with this in mind... still have to do separate packages..

Let me know how it works /
--chris

**Comment by DooblyNoobly** [comment]
Tried all of your suggestions but still receiving same error.

**Comment by kristjank** [comment]
What is the target framework in project settings/ check there if you have mono selected and change to the latest full .Net framework 4.6.2 if I remember correct. I have limited access to computer this week:(

**Comment by kristjank** [comment]
Ok, just did  another test>
1-visual studio 2017
2-opened ark.net.sln file
2-download code and run test
3-all ok

please check your tools and settings/
we have something different... 

right click project settings for ark-net
set target framework 4.5.2

best

**Comment by DooblyNoobly** [comment]
hm, very strange. I changed target to .Net 4.6.2 and retargeted all the packages that gave warnings to do so but same error. Then I retarget back to .Net 4.5.2 but still same error. I also tried on Win10 machine and had same result. Not sure what I could be doing wrong or why my project is different?

![image](https://user-images.githubusercontent.com/20813925/30244436-20dd9712-9601-11e7-86ec-4f217f52151b.png)

**Comment by sharkdev-j** [comment]
I fixed this by downloading Nuget.exe and placing it in ..\ark-net\_CreateNewNuGetPackage\DoNotModify.  The powershell script for building the Nuget package on post build is looking for this.  This will work in windows 10, but will not for mac because it's an exe which is windows only.  If you want to fix this for both platforms you can remove the post build event (delete everything in the box).

![2017-09-23_17-52-00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c70097f3105e001522fc2a/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbec7cf50abdc17b0b77236b48e13b628ae92dbc56395b4d5a47ff425e5716f5f18078a5b76e708a5e5de4d36a0d71c72f0dbefad341eb5ee779c11ac7a4b6984ec0e23c20e78d8d4e3a1d03198afe5e27ed.png)

**Comment by jefferyleo** [comment]
According to @sharkdev-j solution, downloading nuget.exe and place into \ark-net_CreateNewNuGetPackage\DoNotModify is working for me. Thank you!

**Comment by kristjank** [comment]
Awesome work guys!!
