### ISSUE TITLE
Comment the whole API

### ISSUE THREAD

**Issue by Abalalojik** [kristjank/ark-net#71]
Comment the code, give more information about the different functions.
I am already on that.

**Comment by Abalalojik** [comment]
ArkNetAPI ==> done
Attribute ===> done
Controlers ==> done
Core =======> Ongoing
Messages ===> Not done
Models =====> Not done
res =========> Nothing to do (it's images)
Services ====> Not done
Utils =======> Not done

**Comment by kristjank** [comment]
will check in the main repo as discussed
